### ISSUE TITLE
block.json `name` regex pattern doesn't allow slash

### ISSUE THREAD

**Issue by freinbichler** [AdvancedCustomFields/schemas#1]
If you add a prefix to the block name, such as `acf/` or `companyname/`, the validation fails. If you remove the slash, it passes. The regex pattern should allow one slash.

<img width="816" alt="Screenshot" src="https://github.com/AdvancedCustomFields/schemas/assets/118223/7c26b357-5bc3-487c-b710-58d817370daf">

**Comment by onetrev** [comment]
Has anyone found a workaround for this for now while we wait for the merge? Is there anything @polevaultweb holding this up? If so, happy to contribute if possible. It's straining my perfectionist soul to see the ever present warning. :)

**Comment by lgladdy** [comment]
Sorry for the delay @freinbichler @onetrev - my bad for not setting up notifications for new issues/PRs for this repo! Fixed now, and I'll be on top of merges in future!
