### ISSUE TITLE
Schema 504

### ISSUE THREAD

**Issue by vinkla** [AdvancedCustomFields/schemas#6]
The schema URL could not be found. Has the URL been moved to a new location?

> Unable to load schema from 'https://advancedcustomfields.com/schemas/json/main/block.json': HTTP status code 504
error code: 504.(768)

![CleanShot 2024-05-23 at 09 20 20@2x](https://github.com/AdvancedCustomFields/schemas/assets/499192/5cb7f6fe-cafe-43d1-b614-4fa7eaf72de1)

**Comment by lgladdy** [comment]
Hey Vinkla,

Not sure what happened here, but it seems you had a temporary glitch accessing the schema.

It's working okay now, so it may have just been maintenance or a server restart.

Thanks,
Liam

**Comment by vinkla** [comment]
I'm still seeing the issue, do you recommend using the raw GitHub link instead?

**Comment by lgladdy** [comment]
Yeh, you can do: https://raw.githubusercontent.com/AdvancedCustomFields/schemas/main/json/block.json

It's unlikely to change path, but the shortcut from ACF was just there in case we do need to do that at some point.
