### ISSUE TITLE
add usePostMeta and validate properties to acf key ❤️ 

### ISSUE THREAD

**Issue by chrillep** [AdvancedCustomFields/schemas#7]
**validate** (Boolean) (Since 6.3.0) Should the fields in the block be validated as per the field group configuration.
  Default is `true`.

```json
"acf": {
"validate": false
}
```
**usePostMeta** (Boolean) (Since 6.3.0) Should this block store its field values directly in post meta, rather than the block comment. When enabled, this block will be limited to once per page, and only as a top level block. These blocks will also not be supported as widgets or in the site editor/templates.
  Default is `false`.

```json
"acf": {
"usePostMeta": true
}
```

refs:
* https://www.advancedcustomfields.com/resources/acf-block-configuration-via-block-json/#blockjson-acf-key
* https://www.advancedcustomfields.com/resources/save-acf-block-values-to-post-meta/
* https://www.advancedcustomfields.com/blog/acf-6-3-0-released/#acf-blocks-postmeta

**Comment by lgladdy** [comment]
Hey @chrillep,

Thanks for the nudge, I'm a little slow on getting these added, but I'll try and make sure our workflow is updated to release a schema along side new features in future.
