### ISSUE TITLE
Latest commit broke schema

### ISSUE THREAD

**Issue by craigrileyuk** [AdvancedCustomFields/schemas#9]
#8 

There are commas missing at the end of the "description" properties, and errant commas after the "default" value resulting in a completely broken schema.

**Comment by lgladdy** [comment]
Thanks for the heads up @craigrileyuk. This should be fixed now.

**Comment by chrillep** [comment]
whoops my bad 😓

**Comment by lgladdy** [comment]
@chrillep No worries at all! I missed it in review too!

I'll look to get some GitHub actions validation going on PRs so we can make sure everything is valid automatically going forward.
